### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by bryangauvin** [acd/infinitive#30]
Homebridge keeps crashing and I have this in the log. Any ideas what Im doing wrong here?

Config

> {
    "accessory": "Thermostat",
    "name": "Infinitive",
    "apiEndpoint": "http://xxx.xxx.x.xx:8080/api"
}

Log

> SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Thermostat.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-infinitive-thermostat/index.js:373:18)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)

**Comment by jgordon165** [comment]
I was reading about this yesterday. I don't believe that the PR has been merged yet to support tstat/settings

https://github.com/acd/infinitive/pull/24

If you're running the code locally, you might be able to pull this pr down to get your homebridge to work(it would appear that the owner of this repo needs to merge these helpful prs into master)

**Comment by acd** [comment]
This issue pertains to Homebridge, not Infinitive; closing.
